export const bountyAbi = [
  {
    type: 'function',
    name: 'createBounty',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'amount', type: 'uint256' },
      { name: 'repoOwner', type: 'string' },
      { name: 'repoName', type: 'string' },
      { name: 'issueId', type: 'string' },
      { name: 'title', type: 'string' },
    ],
    outputs: [{ name: 'bountyId', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'claimBounty',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'bountyId', type: 'uint256' },
      { name: 'agentDid', type: 'string' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'submitBounty',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'bountyId', type: 'uint256' },
      { name: 'prId', type: 'string' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'approveBounty',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'bountyId', type: 'uint256' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'cancelBounty',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'bountyId', type: 'uint256' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'disputeBounty',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'bountyId', type: 'uint256' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'bounties',
    stateMutability: 'view',
    inputs: [{ name: '', type: 'uint256' }],
    outputs: [
      { name: 'creator', type: 'address' },
      { name: 'amount', type: 'uint256' },
      { name: 'repoOwner', type: 'string' },
      { name: 'repoName', type: 'string' },
      { name: 'issueId', type: 'string' },
      { name: 'title', type: 'string' },
      { name: 'claimantDid', type: 'string' },
      { name: 'claimantAddress', type: 'address' },
      { name: 'prId', type: 'string' },
      { name: 'status', type: 'uint8' },
      { name: 'createdAt', type: 'uint256' },
      { name: 'claimedAt', type: 'uint256' },
      { name: 'submittedAt', type: 'uint256' },
      { name: 'completedAt', type: 'uint256' },
      { name: 'deadline', type: 'uint256' },
    ],
  },
  {
    type: 'function',
    name: 'getAgentStats',
    stateMutability: 'view',
    inputs: [{ name: 'agentDid', type: 'string' }],
    outputs: [
      { name: 'earnings', type: 'uint256' },
      { name: 'completedCount', type: 'uint256' },
    ],
  },
  {
    type: 'function',
    name: 'getProtocolStats',
    stateMutability: 'view',
    inputs: [],
    outputs: [
      { name: 'totalBounties', type: 'uint256' },
      { name: 'totalPaidOut', type: 'uint256' },
      { name: 'totalFeesCollected', type: 'uint256' },
    ],
  },
  {
    type: 'function',
    name: 'nextBountyId',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'event',
    name: 'BountyCreated',
    anonymous: false,
    inputs: [
      { name: 'bountyId', type: 'uint256', indexed: true },
      { name: 'creator', type: 'address', indexed: true },
      { name: 'amount', type: 'uint256', indexed: false },
      { name: 'repoOwner', type: 'string', indexed: false },
      { name: 'repoName', type: 'string', indexed: false },
      { name: 'issueId', type: 'string', indexed: false },
      { name: 'title', type: 'string', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'BountyClaimed',
    anonymous: false,
    inputs: [
      { name: 'bountyId', type: 'uint256', indexed: true },
      { name: 'claimantDid', type: 'string', indexed: false },
      { name: 'claimantAddress', type: 'address', indexed: true },
    ],
  },
  {
    type: 'event',
    name: 'BountySubmitted',
    anonymous: false,
    inputs: [
      { name: 'bountyId', type: 'uint256', indexed: true },
      { name: 'prId', type: 'string', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'BountyCompleted',
    anonymous: false,
    inputs: [
      { name: 'bountyId', type: 'uint256', indexed: true },
      { name: 'claimant', type: 'address', indexed: true },
      { name: 'payout', type: 'uint256', indexed: false },
      { name: 'fee', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'BountyCancelled',
    anonymous: false,
    inputs: [{ name: 'bountyId', type: 'uint256', indexed: true }],
  },
  {
    type: 'event',
    name: 'BountyDisputed',
    anonymous: false,
    inputs: [{ name: 'bountyId', type: 'uint256', indexed: true }],
  },
] as const
