'use client'

import { useScoutAnalysis } from '@/hooks/useScoutAnalysis'
import { BlinkingCursor } from './ui/BlinkingCursor'

const DIFFICULTY_COLOR: Record<string, string> = {
  easy: 'text-status-open',
  medium: 'text-status-claimed',
  hard: 'text-status-disputed',
  legendary: 'text-status-completed',
}

const ALPHA_COLOR: Record<string, string> = {
  underpriced: 'text-status-open',
  fair: 'text-muted',
  overpriced: 'text-status-disputed',
}

export function BountyScout({ bountyId }: { bountyId: number }) {
  const { data, isLoading, error } = useScoutAnalysis(bountyId)

  return (
    <section className="border border-border p-4 space-y-3">
      <div className="flex items-baseline justify-between">
        <h2 className="text-sm uppercase tracking-wider text-muted">
          <span className="text-accent">◇</span> bounty scout analysis
        </h2>
        <span className="text-xs text-muted">$ scout #{bountyId}</span>
      </div>

      {isLoading && <BlinkingCursor label="$ analyzing bounty" />}

      {error && (
        <div className="text-status-disputed text-sm">
          ERR: scout unavailable. {String((error as Error).message).slice(0, 80)}
        </div>
      )}

      {data && (
        <div className="space-y-3 text-sm">
          <div className="text-primary">{data.tldr}</div>

          <div className="grid grid-cols-2 gap-x-6 gap-y-2 text-xs">
            <Row label="difficulty" value={<span className={DIFFICULTY_COLOR[data.difficulty]}>{data.difficulty}</span>} />
            <Row label="effort" value={data.estimatedEffort} />
            <Row label="alpha" value={<span className={ALPHA_COLOR[data.alphaRating]}>{data.alphaRating}</span>} />
            <Row label="skills" value={data.skills.join(', ')} />
          </div>

          <div className="text-xs text-muted border-t border-border pt-3">
            <div className="text-primary mb-1">alpha reason</div>
            {data.alphaReason}
          </div>

          {data.pitfalls.length > 0 && (
            <div className="text-xs text-muted border-t border-border pt-3">
              <div className="text-primary mb-1">pitfalls</div>
              <ul className="list-none space-y-0.5">
                {data.pitfalls.map((p, i) => (
                  <li key={i}>
                    <span className="text-status-disputed">!</span> {p}
                  </li>
                ))}
              </ul>
            </div>
          )}

          <div className="text-[10px] text-muted">
            generated by Llama 3.3 70B · {new Date(data.generatedAt).toLocaleString()}
          </div>
        </div>
      )}
    </section>
  )
}

function Row({ label, value }: { label: string; value: React.ReactNode }) {
  return (
    <div className="flex items-baseline gap-2">
      <span className="text-muted uppercase">{label}</span>
      <span>{value}</span>
    </div>
  )
}
